---
name: other

services:

  watchyourlan:
    image: aceberg/watchyourlan:latest
    container_name: watchyourlan
    volumes:
      - /homeserver/watchyourlan/data:/data/WatchYourLAN
    network_mode: host
    env_file:
      - /homeserver/.env
      - /homeserver/watchyourlan/.env
    healthcheck:
      test: wget -nv -t1 --spider http://localhost:8840 || exit 1
      interval: 1m
      start_period: 20s
      timeout: 10s
      retries: 3
    restart: unless-stopped
