name: filebrowser
services:
  filebrowser:
    image: gtstef/filebrowser:stable
    container_name: filebrowser
    volumes:
      - /fjellheimen/data/filebrowser:/home/filebrowser/data
      - /xdrive/Syncthing:/xdrive/syncthing:ro
      - /xdrive/Data/Documents:/xdrive/documents:ro
    networks:
      - reverse-proxy
    extra_hosts:
      - auth.fjellhei.men:172.20.0.2
    env_file:
      - /fjellheimen/stacks/.env
    labels:
      traefik.enable: "true"
      traefik.http.routers.filebrowser.rule: Host(`files.fjellhei.men`)
      traefik.http.routers.filebrowser.entrypoints: websecure
      traefik.http.routers.filebrowser.middlewares: voidauth@docker
      traefik.http.services.filebrowser.loadbalancer.server.port: "80"
    healthcheck:
      test: wget -nv -t1 --spider http://localhost:80 || exit 1
      interval: 1m
      start_period: 20s
      timeout: 10s
      retries: 3
    restart: unless-stopped
networks:
  reverse-proxy:
    external: true
