---
name: other

services:

  note-pls:
    image: ghcr.io/fjelloverflow/note-pls:latest
    container_name: note-pls
    volumes:
      - /xdrive/Syncthing/Notes/0 - Inbox:/inbox
    env_file:
      - /homeserver/.env
      - /homeserver/note-pls/.env
    environment:
      NP_FILEPATH: /inbox/TODOs.md
      NP_PREPEND:  "\
      
        - "
    restart: unless-stopped
