[global]

   workgroup = WORKGROUP
   server role = standalone server

   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file

   map to guest = never

[fjellheimen]
    comment = Fjellheimen home directory
    path = /fjellheimen
    read only = yes
    browsable = yes
    write list = {{ target_user }}

[xdrive]
    comment = Fjellheimen external drive
    path = /xdrive
    read only = yes
    browsable = yes
    write list = {{ target_user }}
