version: '3'

name: homeserver

services:

  mealie:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    container_name: mealie
    volumes:
      - /homeserver/mealie/data/config:/app/data/
    networks:
      - proxy-network
      - mealie-network
    env_file:
      - /homeserver/.env
      - /homeserver/mealie/.env
    environment:
      - API_URL=http://mealie-api:9000
    restart: unless-stopped
  
  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    container_name: mealie-api
    volumes:
      - /homeserver/mealie/data/config:/app/data/
    networks:
      - mealie-network
    env_file:
      - /homeserver/.env
      - /homeserver/mealie/.env
    environment:
      - ALLOW_SIGNUP=true
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
    restart: unless-stopped

networks:
  mealie-network:
  proxy-network:
    external: true