---
name: other

services:

  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    volumes:
      - /fjellheimen/mealie/data/config:/app/data/
    networks:
      - proxy-network
    env_file:
      - /fjellheimen/.env
    environment:
      - ALLOW_SIGNUP=true
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - TOKEN_TIME=744
    restart: unless-stopped

networks:
  proxy-network:
    external: true
