---
name: other

services:

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    volumes:
      - /fjellheimen/audiobookshelf/data/config:/config
      - /fjellheimen/audiobookshelf/data/metadata:/metadata
      - /xdrive/Media/Audiobooks:/audiobooks
      - /xdrive/Media/Podcasts:/podcasts
    networks:
      - proxy-network
    env_file:
      - /fjellheimen/.env
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 1m
      start_period: 20s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  proxy-network:
    external: true
