name: dockge
services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    user: 1000:1000
    group_add:
      - "996"
    volumes:
      - /fjellheimen/data/dockge:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /fjellheimen/stacks:/fjellheimen/stacks
    networks:
      - reverse-proxy
    env_file:
      - /fjellheimen/stacks/.env
    environment:
      DOCKGE_STACKS_DIR: /fjellheimen/stacks
    labels:
      traefik.enable: "true"
      traefik.http.routers.dockge.rule: Host(`containers.fjellhei.men`)
      traefik.http.routers.dockge.entrypoints: websecure
      traefik.http.routers.dockge.middlewares: voidauth@docker
      traefik.http.services.dockge.loadbalancer.server.port: "5001"
    restart: unless-stopped
networks:
  reverse-proxy:
    external: true
