name: vaultwarden
services:
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:latest
    container_name: vaultwarden
    volumes:
      - /fjellheimen/data/vaultwarden:/data
    networks:
      - reverse-proxy
    extra_hosts:
      - auth.fjellhei.men:172.20.0.2
    env_file:
      - /fjellheimen/stacks/.env
      - /fjellheimen/stacks/vaultwarden/.env
    labels:
      traefik.enable: "true"
      traefik.http.routers.vaultwarden.rule: Host(`passwords.fjellhei.men`)
      traefik.http.routers.vaultwarden.entrypoints: websecure
      traefik.http.services.vaultwarden.loadbalancer.server.port: "80"
    restart: unless-stopped
networks:
  reverse-proxy:
    external: true
