---
name: other

services:

  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:latest
    container_name: vaultwarden
    volumes:
      - /fjellheimen/vaultwarden/data:/data
    networks:
      - proxy-network
    env_file:
      - /fjellheimen/.env
    restart: unless-stopped

networks:
  proxy-network:
    external: true
