---

- name: Add backup cronjob
  become: false
  ansible.builtin.cron:
    name: "Run backup job"
    minute: "0"
    hour: "4"
    weekday: "5"
    job: "/fjellheimen/jobs/backup"

- name: Add IP check cronjob
  become: false
  ansible.builtin.cron:
    name: "Check for IP change"
    minute: "0"
    hour: "0"
    job: "/fjellheimen/jobs/check_public_ip"

- name: Add container update check cronjob
  become: false
  ansible.builtin.cron:
    name: "Check for container updates"
    minute: "0"
    hour: "4"
    weekday: "6"
    job: "/fjellheimen/jobs/check_container_updates"

- name: Add server boot cronjob
  become: false
  ansible.builtin.cron:
    name: "Job on server start"
    special_time: "reboot"
    job: "/fjellheimen/jobs/on_startup"