---
- name: Update packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: 'yes'

- name: Install curl, wget, git, tmux, ncdu
  ansible.builtin.apt:
    package:
      - curl
      - wget
      - git
      - tmux
      - ncdu
