---
- name: Clone fjellheimen repo # noqa: latest - re-runs dont  refetch
  ansible.builtin.git:
    repo: "https://github.com/FjellOverflow/fjellheimen.git"
    dest: "{{ target_home }}/fjellheimen"
    update: false

- name: Symlink /fjellheimen
  become: true
  ansible.builtin.file:
    src: "{{ target_home }}/fjellheimen"
    dest: "/fjellheimen"
    state: link
