---
- name: Install git
  ansible.builtin.apt:
    package: git

- name: Clone fjellheimen repo
  become: false
  ansible.builtin.git:
    repo: 'https://github.com/FjellOverflow/fjellheimen.git'
    dest: "/home/{{username}}/fjellheimen"

- name: Symlink /fjellheimen 
  file:
    src: "/home/{{username}}/fjellheimen"
    dest: "/fjellheimen"
    state: link