---
# instructions: https://tailscale.com/kb/1174/install-debian-bookworm

- name: Add tailscale gpg key
  ansible.builtin.uri:
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    creates: /usr/share/keyrings/tailscale-archive-keyring.gpg
    url: https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg 

- name: Add tailscale repository
  ansible.builtin.uri:
    dest: /etc/apt/sources.list.d/tailscale.list
    creates: /etc/apt/sources.list.d/tailscale.list
    url: https://pkgs.tailscale.com/stable/debian/bookworm.tailscale-keyring.list

- name: Install tailscale
  ansible.builtin.apt:
    update_cache: yes
    package:
      - tailscale