---
- name: Install ufw
  ansible.builtin.apt:
    package: ufw

- name: Copy app profiles
  copy:
    src: "templates/ufw/"
    dest: "/etc/ufw/applications.d/"

- name: Allow ssh in ufw
  community.general.ufw:
    rule: allow
    name: 'ssh'

- name: Allow plex in ufw
  community.general.ufw:
    rule: allow
    name: 'plex'

- name: Allow watchyourlan in ufw
  community.general.ufw:
    rule: allow
    name: 'watchyourlan'

- name: Enable ufw
  community.general.ufw:
    state: enabled