---
# https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest:  "/home/{{username}}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

# https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md
- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest:  "/home/{{username}}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Write .zshrc
  copy:
    src: "templates/.zshrc"
    dest: "/home/{{username}}/.zshrc"        
