name: homepage
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    user: 1000:1000
    group_add:
      - "996"
    volumes:
      - /fjellheimen/data/homepage/config:/app/config
      - /fjellheimen/data/homepage/assets:/app/public/assets
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - reverse-proxy
    env_file:
      - /fjellheimen/stacks/homepage/.env
    labels:
      traefik.enable: "true"
      traefik.http.routers.homepage.rule: Host(`fjellhei.men`)
      traefik.http.routers.homepage.entrypoints: websecure
      traefik.http.routers.homepage.middlewares: voidauth@docker
      traefik.http.services.homepage.loadbalancer.server.port: "3000"
    restart: unless-stopped
networks:
  reverse-proxy:
    external: true
