---
name: core

services:

  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: core-npm
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /fjellheimen/core/data/npm/data:/data
      - /fjellheimen/core/data/npm/letsencrypt:/etc/letsencrypt
    networks:
      - proxy-network
    env_file:
      - /fjellheimen/.env
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:sts
    container_name: core-portainer
    volumes:
      - /fjellheimen/core/data/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy-network
    env_file:
      - /fjellheimen/.env
    privileged: true
    restart: unless-stopped

networks:
  proxy-network:
    name: proxy-network
