---
name: bookmarks

services:

  readeck:
    image: codeberg.org/readeck/readeck:latest
    container_name: bookmarks-readeck
    volumes:
      - /homeserver/bookmarks/data/readeck:/readeck
    networks:
      - proxy-network
    env_file:
      - /homeserver/.env
    environment:
      - READECK_USE_X_FORWARDED=true
    healthcheck:
      test: ["CMD", "/bin/readeck", "healthcheck", "-config", "config.toml"]
      interval: 30s
      timeout: 2s
      retries: 3
    restart: unless-stopped

  linkding:
    image: sissbruecker/linkding:latest
    container_name: bookmarks-linkding
    volumes:
      - /homeserver/bookmarks/data/linkding:/etc/linkding/data
    networks:
      - proxy-network
    env_file:
      - /homeserver/.env
    healthcheck:
      test: curl --fail http://localhost:9090 || exit 1
      interval: 1m
      start_period: 20s
      timeout: 10s
      retries: 3
    restart: unless-stopped


networks:
  proxy-network:
    external: true
