---
- Providers:
  - Tailscale:
    - icon: sh-tailscale-light
      href: https://login.tailscale.com/admin
  - Porkbun:
    - icon: sh-porkbun-light
      href: https://porkbun.com/

- Fjellheimen:
  - Git repository:
    - icon: sh-github-light
      href: https://github.com/FjellOverflow/fjellheimen
  - Fjellside:
      - icon: mdi-image-filter-hdr-#ffffff
        href: {{HOMEPAGE_VAR_FJELLSIDE_URL}}

- Resources:
  - Homepage documentation:
    - icon: si-homepage-#ffffff
      href: https://gethomepage.dev/
  - selfh.st Directory:
    - icon: sh-selfh-st-light
      href: https://selfh.st/apps/
