---
title: Fjellheimen
background:
  image: /assets/background.png
  blur: xs
  opacity: 15
hideErrors: true
statusStyle: dot
maxGroupColumns: 5
layout:
  Media:
    icon: mdi-multimedia
  Automation:
    icon: mdi-download
  Personal Data:
    icon: mdi-file-cabinet
  Tools:
    icon: mdi-tools
  Infrastructure:
    icon: mdi-account-wrench
  Providers:
    icon: mdi-server-outline
  Fjellheimen:
    icon: mdi-image-filter-hdr-outline
  Resources:
    icon: mdi-school-outline
