title: Fjellheimen
background:
  image: /assets/background.png
  blur: xs
  opacity: 15
hideErrors: true
statusStyle: dot
maxGroupColumns: 5
disableCollapse: true
layout:
  Media:
    icon: mdi-multimedia
    style: row
    columns: 3
  Media Management:
    icon: mdi-download-box
    style: row
    columns: 3
  Personal:
    header: false
    style: row
    columns: 3
    Photos:
      icon: mdi-image-multiple
      style: column
    Development:
      icon: mdi-code-tags
      style: column
    Files:
      icon: mdi-folder-multiple
      style: column
  Organization:
    icon: mdi-view-dashboard
    style: row
    columns: 5
  Infrastructure:
    icon: mdi-account-wrench
    style: row
    columns: 5
