name: forgejo
services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:15
    container_name: forgejo
    volumes:
      - /fjellheimen/data/forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - reverse-proxy
    extra_hosts:
      - auth.fjellhei.men:172.20.0.2
    env_file:
      - /fjellheimen/stacks/.env
    labels:
      traefik.enable: "true"
      traefik.http.routers.forgejo.rule: Host(`forge.fjellhei.men`)
      traefik.http.routers.forgejo.entrypoints: websecure
      traefik.http.routers.forgejo.middlewares: voidauth@docker
      traefik.http.services.forgejo.loadbalancer.server.port: "3000"
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 1m
      start_period: 20s
      timeout: 10s
      retries: 3
    restart: unless-stopped
networks:
  reverse-proxy:
    external: true
