version: '3'

name: homeserver

services:

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: server-nginx-proxy-manager
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /homeserver/server/data/nginx-proxy-manager/data:/data
      - /homeserver/server/data/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - proxy-network
    env_file:
      - /homeserver/.env
      - /homeserver/server/.env
      - /homeserver/server/nginx-proxy-manager.env
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    restart: unless-stopped

  portainer:
    image: portainer/portainer:latest
    container_name: server-portainer
    volumes:
      - /homeserver/server/data/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy-network
    env_file:
      - /homeserver/.env
      - /homeserver/server/.env
      - /homeserver/server/portainer.env
    privileged: true
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    container_name: server-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy-network
    env_file:
      - /homeserver/.env
      - /homeserver/server/.env
      - /homeserver/server/watchtower.env
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_SCHEDULE=0 0 4 * * SAT
    restart: unless-stopped

networks:
  proxy-network:
    name: proxy-network
