#!/bin/bash

# called Friday, 4:00 AM

# load ENV
CURRENT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $CURRENT_DIR/.env

NOTIFY=$CURRENT_DIR/notify

$NOTIFY "Backing up $BACKUP_SOURCE to $BACKUP_DESTINATION."

sudo borg create $BACKUP_DESTINATION::{hostname}-{now} $BACKUP_SOURCE
sudo chown -R $BACKUP_USER:$BACKUP_USER $BACKUP_DESTINATION/

$NOTIFY "Backup finished."
