#!/bin/bash

# called Friday, 4:00 AM

# load ENV
CURRENT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $CURRENT_DIR/.env

NOTIFY=$CURRENT_DIR/notify

$NOTIFY "Backing up $SOURCE_FOLDER to $BACKUP_FOLDER."

sudo borg create $BACKUP_FOLDER::{hostname}-{now} $SOURCE_FOLDER

$NOTIFY "Backup finished."
