#!/usr/bin/env bash

# called every day, 0:00 AM

# load ENV
CURRENT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $CURRENT_DIR/.env

NOTIFY=$CURRENT_DIR/notify

FILENAME=$CURRENT_DIR/.last_public_ip
LAST_IP="/"
CURRENT_IP=$(wget -O - -q https://checkip.amazonaws.com)

if [ -f "$FILENAME" ]; then
    LAST_IP=$(cat "$FILENAME")
else
    touch $FILENAME
fi

if [ ! "$LAST_IP" == "$CURRENT_IP" ]; then
    echo $CURRENT_IP > $FILENAME
    $NOTIFY "Public IP change detected!
Old IP: $LAST_IP
New IP: $CURRENT_IP
Update DNS records now at $DNS_PROVIDER"
fi
