#!/usr/bin/env bash

# load ENV
CURRENT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $CURRENT_DIR/.env

# Notify using Telegram
curl -s -X POST \
     "https://api.telegram.org/bot$NOTIFY_TELEGRAM_BOT_TOKEN/sendMessage" \
     --data-urlencode "chat_id=$NOTIFY_TELEGRAM_CHAT_ID" \
     --data-urlencode "text=$1"
