#!/usr/bin/env bash

# load ENV
CURRENT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $CURRENT_DIR/.env

# Notify using Telegram
curl -X POST \
     -H 'Content-Type: application/json' \
     -d "{\"chat_id\": \"$TELEGRAM_CHAT_ID\", \"text\": \"$1\"}" \
     "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage"

