#!/usr/bin/env bash

# called at reboot

# load ENV
CURRENT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $CURRENT_DIR/.env

NOTIFY=$CURRENT_DIR/notify

# wait until docker started containers
#sleep 2m


STOPPED_CONTAINERS=$(docker ps -a --filter "status=exited" --format '{{.Names}}')
DRIVE_MOUNTED=""

if [ -n "$STOPPED_CONTAINERS" ]; then
    STOPPED_CONTAINERS="Stopped containers: "$STOPPED_CONTAINERS
else
    STOPPED_CONTAINERS="All containers running."
fi

if ! findmnt "$DRIVE_PATH" > /dev/null; then
    DRIVE_MOUNTED="$DRIVE_PATH is not mounted."
fi

$NOTIFY "Server booted up.
$STOPPED_CONTAINERS
$DRIVE_MOUNTED"

