#!/usr/bin/env bash

# called at reboot

# load ENV
CURRENT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $CURRENT_DIR/.env

NOTIFY=$CURRENT_DIR/notify

# wait until docker started containers
sleep 2m


RUNNING_CONTAINERS=$(sudo docker ps -a --filter "status=exited" --format "{{.Names}}")
XDRIVE_MOUNTED="/xdrive is not mounted."

if findmnt "/xdrive" > /dev/null; then
    XDRIVE_MOUNTED=""
fi

$NOTIFY "Server booted up. Stopped containers:
$RUNNING_CONTAINERS
$XDRIVE_MOUNTED"

