#!/usr/bin/env bash

# called Sundays, 4:00 AM

# load ENV
CURRENT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $CURRENT_DIR/.env

NOTIFY=$CURRENT_DIR/notify

$NOTIFY "Rebooting server."

# wait for notification to go out
sleep 10s

sudo systemctl reboot
