version: '3'

name: homeserver

services:

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf
    container_name: audiobookshelf
    volumes:
      - /homeserver/data/audiobookshelf/config:/config
      - /homeserver/data/audiobookshelf/metadata:/metadata
      - /mediadrive/Audiobooks:/audiobooks
    networks:
      - proxy-network
    env_file:
      - /homeserver/environment/general.env
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 1m
      start_period: 20s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  proxy-network:
    external: true
