version: '3'

name: homeserver

services:

  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    volumes:
      - /homeserver/data/kavita/config:/config
      - /mediadrive/Books:/data
    networks:
      - proxy-network
    env_file:
      - /homeserver/environment/general.env
    healthcheck:
      test: curl --fail http://localhost:5000 || exit 1
      interval: 1m
      start_period: 20s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  proxy-network:
    external: true