version: '3'

name: homeserver

services:
  
  memos:
    image: neosmemo/memos:latest
    container_name: memos
    volumes:
      - /homeserver/data/memos/config:/var/opt/memos
    networks:
      - proxy-network
    env_file:
      - /homeserver/environment/general.env
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5230 || exit 1
      interval: 1m
      start_period: 20s
      timeout: 10s
      retries: 3

networks:
  proxy-network:
    external: true