version: "3"

name: homeserver

services:

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - /homeserver/data/radarr/config:/config
      - /mediadrive/Movies:/movies
      - /mediadrive/Downloads:/downloads
    networks:
      - proxy-network
    env_file:
      - /homeserver/environment/general.env
    healthcheck:
      test: curl --fail http://localhost:7878 || exit 1
      interval: 1m
      start_period: 20s
      timeout: 10s
      retries: 3

networks:
  proxy-network:
    external: true
