version: '3'

name: homeserver

services:

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: server-nginx-proxy-manager
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /homeserver/data/nginx-proxy-manager/data:/data
      - /homeserver/data/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - proxy-network
    env_file:
      - /homeserver/environment/general.env
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    restart: unless-stopped

  portainer:
    image: portainer/portainer:latest
    container_name: server-portainer
    volumes:
      - /homeserver/data/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy-network
    env_file:
      - /homeserver/environment/general.env
    privileged: true
    restart: unless-stopped

  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: server-homepage
    volumes:
      - /homeserver/data/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mediadrive:/mediadrive
      - /homeserver:/homeserver
    networks:
      - proxy-network
    env_file:
      - /homeserver/environment/homepage_dedyn.env
    environment:
      - TZ=Europe/Tallinn
    restart: unless-stopped

  glances:
    image: nicolargo/glances:latest
    container_name: server-glances
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-network
    env_file:
      - /homeserver/environment/general.env
    environment:
      - GLANCES_OPT=-w
    privileged: true
    pid: host
    healthcheck:
      test: curl --fail -s http://localhost:61208 || exit 1
      interval: 1m
      start_period: 20s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: server-duckdns
    networks:
      - proxy-network
    env_file:
      - /homeserver/environment/general.env
      - /homeserver/environment/duckdns.env
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    container_name: server-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy-network
    env_file:
      - /homeserver/environment/general.env
    restart: unless-stopped

networks:
  proxy-network:
    name: proxy-network