name: apprise
services:
  apprise:
    image: caronc/apprise:latest
    container_name: apprise
    ports:
      - 8000:8000
    volumes:
      - /fjellheimen/data/apprise/config:/config
      - /fjellheimen/data/apprise/attach:/attach
    networks:
      - reverse-proxy
    env_file:
      - /fjellheimen/stacks/.env
    environment:
      APPRISE_STATEFUL_MODE: simple
      APPRISE_WORKER_COUNT: 1
      APPRISE_ADMIN: yes
    labels:
      traefik.enable: "true"
      traefik.http.routers.apprise.rule: Host(`notifications.fjellhei.men`)
      traefik.http.routers.apprise.entrypoints: websecure
      traefik.http.routers.apprise.middlewares: voidauth@docker
      traefik.http.services.apprise.loadbalancer.server.port: "8000"
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 1m
      start_period: 20s
      timeout: 10s
      retries: 3
    restart: unless-stopped
networks:
  reverse-proxy:
    external: true
