---
name: other

services:

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    volumes:
      - /fjellheimen/syncthing/data/config:/config
      - /xdrive/Syncthing:/data
    networks:
      - proxy-network
    env_file:
      - /fjellheimen/.env
    healthcheck:
      test: curl --fail http://localhost:8384 || exit 1
      interval: 1m
      start_period: 20s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  proxy-network:
    external: true
