version: "3"

name: homeserver

services:

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    volumes:
      - /homeserver/syncthing/data/config:/config
      - /xdrive/Syncthing:/data
    networks:
      - proxy-network
    env_file:
      - /homeserver/.env
      - /homeserver/syncthing/.env
    restart: unless-stopped

networks:
  proxy-network:
    external: true