name: audiobookshelf
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    volumes:
      - /fjellheimen/data/audiobookshelf/config:/config
      - /fjellheimen/data/audiobookshelf/metadata:/metadata
      - /xdrive/Media/Audiobooks:/audiobooks
      - /xdrive/Media/Podcasts:/podcasts
    networks:
      - reverse-proxy
    extra_hosts:
      - auth.fjellhei.men:172.20.0.2
    env_file:
      - /fjellheimen/stacks/.env
    labels:
      traefik.enable: "true"
      traefik.http.routers.audiobooks.rule: Host(`audiobooks.fjellhei.men`)
      traefik.http.routers.audiobooks.entrypoints: websecure
      traefik.http.services.audiobooks.loadbalancer.server.port: "80"
    healthcheck:
      test: wget -nv -t1 --spider http://localhost:80 || exit 1
      interval: 1m
      start_period: 20s
      timeout: 10s
      retries: 3
    restart: unless-stopped
networks:
  reverse-proxy:
    external: true
