---
name: other

services:

  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    volumes:
      - /fjellheimen/nocodb/data:/usr/app/data/
    networks:
      - proxy-network
    env_file:
      - /fjellheimen/.env
    healthcheck:
      test: curl --fail http://localhost:8080/dashboard || exit 1
      interval: 1m
      start_period: 20s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  proxy-network:
    external: true
