version: "3"

name: torrents

services:

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: torrents-qbittorrent
    volumes:
      - /homeserver/torrents/data//qbittorrent/config:/config
      - /xdrive/Media/Downloads:/downloads
    network_mode: "service:gluetun"
    env_file:
      - /homeserver/.env
    environment:
      - WEBUI_PORT=9090
    depends_on:
      - gluetun
    healthcheck:
      test: curl --fail http://localhost:9090 || exit 1
      interval: 1m
      start_period: 20s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    labels:
      io.portainer.accesscontrol.public: true

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: torrents-gluetun
    cap_add:
      - NET_ADMIN
    expose:
      - '9090'
    networks:
      - proxy-network
    env_file:
      - /homeserver/.env
      - /homeserver/torrents/gluetun.env
    environment:
      - VPN_TYPE=openvpn
    restart: unless-stopped
    labels:
      io.portainer.accesscontrol.public: true

networks:
  proxy-network:
    external: true
